name: 'Install Solana'
description: 'Install Solana CLI'

runs:
  using: "composite"
  steps:
    - name: Cache Solana Install
      id: cache-solana
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/solana
          ~/.local/share/solana
          ~/.solana
        key: ${{ runner.os }}-solana

    - name: Install Solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        source "$HOME/.cargo/env"
        solana --version
        solana-keygen new --no-bip39-passphrase
        
        cargo install --git https://github.com/coral-xyz/anchor avm --force
        avm install 0.30.1
        avm use 0.30.1
        anchor --version
