[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ca_registrar = "6rsq6P7d7WH1zF3DWJYzcfxTprUdL5q25AcXw8ZoCvDo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
